# Generated by Django 4.0.2 on 2022-02-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_articolo_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='autore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.autore'),
        ),
    ]
