# Generated by Django 4.0.2 on 2022-02-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_articolo_autore'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='genere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.genere'),
        ),
    ]
