# Generated by Django 4.0.2 on 2022-02-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_articolo_genere_articolo_genere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterModelOptions(
            name='autore',
            options={'verbose_name': 'Autore', 'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='genere',
            options={'verbose_name': 'Genere', 'verbose_name_plural': 'Generi'},
        ),
    ]
